### getService
POST http://localhost:6555/rpc-01_default_dev_com_zst_rpc_demo_api_UserService/
Content-Type: application/json

{
  "service": "rpc-01_default_dev_com_zst_rpc_demo_api_UserService",
  "method": "com.zst.rpc.demo.api.UserService#findById(String)",
  "args": [
    "1"
  ]
}

### g
GET http://localhost:6555/rpc-01_default_dev_com_zst_rpc_demo_api_UserService/